name = "smilecters" 
type = "javascript" 
account_id = "12adc4f2f6e755f1daf67b3038c3d6a5" 
workers_dev = true 
main = "worker.js"

kv_namespaces = [
  { binding = "name-database", id = "0c5793104d3846b1aed1d2a9451886be" }
]